### ISSUE TITLE
Release of data

### ISSUE THREAD

**Issue by CyberTimon** [jphme/EM_German#1]
Hello

Thank you for this amazing model. The model works very well with german. 
I really want to train MythoMax 13b on this german data to keep the intelligence / rp capabilities but be able to talk in german. 

Do you have a problem with releasing the data or do you plan to do so?
Thank you very much

Kind regards,
Timon Käch

**Comment by jphme** [comment]
> Hello
> 
> Thank you for this amazing model. The model works very well with german. I really want to train MythoMax 13b on this german data to keep the intelligence / rp capabilities but be able to talk in german.
> 
> Do you have a problem with releasing the data or do you plan to do so? Thank you very much
> 
> Kind regards, Timon Käch

Thanks for your question - I am planning to release most of the datasets used to train EM German, I just have to do some cleaning and sanitizing to get them into a useful/shareable state and am currently quite busy with other stuff; so it could take a while. (if you have specific questions/ideas in the meantime, please write an E-Mail)
