### ISSUE TITLE
Broken Links for Mistral LeoLM

### ISSUE THREAD

**Issue by joklaff** [jphme/EM_German#2]
Hi!
First of all: Thank you for the amazing work! 

Secondly: I was about to try out the mistral-LeoLM combination as I was super curious and eagerly waiting for someone with the necessary compute to adapt mistral with the LeoLM datasets,  but unfortunately it seems like the links in the repo are broken. Am I missing something or could you maybe double check?

Cheers, 
Jonas

**Comment by jphme** [comment]
@joklaff thanks for letting me know. I just updated the links (and TheBloke´s GGUF upload seems to have failed, you could try [my own quants](https://huggingface.co/jphme/em_german_leo_mistral_gguf) until this is fixed), all other links should work now!
