### ISSUE TITLE
Please benchmark the model with MT-Bench-DE

### ISSUE THREAD

**Issue by h3ndrik** [jphme/EM_German#4]
So we can compare it to models like the https://huggingface.co/LeoLM/leo-hessianai-13b-chat

I think they mentioned their approach here (in "Evaluation and Results"):
https://laion.ai/blog/leo-lm/

**Comment by jphme** [comment]
Short update on this: There is some work on the benchmark side and we will probably have significant better benchmarks (and maybe even some kind of Leaderboard) for non-english models soon, stay tuned. If you have any specific questions (or suggestions for evals) in the meantime, feel free to contact me.

**Comment by h3ndrik** [comment]
Thanks. Awesome! Yeah, I'm not an expert on this. It's unlikely I can contribute anything if substance. I'm going to stick around.
